yarnPath: .yarn/releases/yarn-4.1.1.cjs
nodeLinker: node-modules
nmMode: hardlinks-local

npmScopes:
  prompteus-ai:
    npmPublishRegistry: https://npm.pkg.github.com
    npmAuthToken: ${NODE_AUTH_TOKEN}